package com.example.mapper.cost;

import com.example.domain.cost.HadCostCategory;
import com.example.example.cost.HadCostCategoryExample;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HadCostCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table had_cost_categories
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int countByExample(HadCostCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table had_cost_categories
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int deleteByExample(HadCostCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table had_cost_categories
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table had_cost_categories
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int insert(HadCostCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table had_cost_categories
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int insertSelective(HadCostCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table had_cost_categories
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    List<HadCostCategory> selectByExample(HadCostCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table had_cost_categories
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    HadCostCategory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table had_cost_categories
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByExampleSelective(@Param("record") HadCostCategory record, @Param("example") HadCostCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table had_cost_categories
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByExample(@Param("record") HadCostCategory record, @Param("example") HadCostCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table had_cost_categories
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByPrimaryKeySelective(HadCostCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table had_cost_categories
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByPrimaryKey(HadCostCategory record);
}