package com.example.mapper.cost;

import com.example.domain.cost.SplitMember;
import com.example.example.cost.SplitMemberExample;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SplitMemberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table split_members
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int countByExample(SplitMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table split_members
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int deleteByExample(SplitMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table split_members
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table split_members
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int insert(SplitMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table split_members
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int insertSelective(SplitMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table split_members
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    List<SplitMember> selectByExample(SplitMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table split_members
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    SplitMember selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table split_members
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByExampleSelective(@Param("record") SplitMember record, @Param("example") SplitMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table split_members
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByExample(@Param("record") SplitMember record, @Param("example") SplitMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table split_members
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByPrimaryKeySelective(SplitMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table split_members
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByPrimaryKey(SplitMember record);
}