package com.example.domain.memory;

import java.util.Date;

public class Memory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memories.id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memories.shiori_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private Integer shioriId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memories.user_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memories.title
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memories.content
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memories.is_public_sche
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private Byte isPublicSche;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memories.post_at
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private Date postAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memories.id
     *
     * @return the value of memories.id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memories.id
     *
     * @param id the value for memories.id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memories.shiori_id
     *
     * @return the value of memories.shiori_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public Integer getShioriId() {
        return shioriId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memories.shiori_id
     *
     * @param shioriId the value for memories.shiori_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setShioriId(Integer shioriId) {
        this.shioriId = shioriId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memories.user_id
     *
     * @return the value of memories.user_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memories.user_id
     *
     * @param userId the value for memories.user_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memories.title
     *
     * @return the value of memories.title
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memories.title
     *
     * @param title the value for memories.title
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memories.content
     *
     * @return the value of memories.content
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memories.content
     *
     * @param content the value for memories.content
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memories.is_public_sche
     *
     * @return the value of memories.is_public_sche
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public Byte getIsPublicSche() {
        return isPublicSche;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memories.is_public_sche
     *
     * @param isPublicSche the value for memories.is_public_sche
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setIsPublicSche(Byte isPublicSche) {
        this.isPublicSche = isPublicSche;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memories.post_at
     *
     * @return the value of memories.post_at
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public Date getPostAt() {
        return postAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memories.post_at
     *
     * @param postAt the value for memories.post_at
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setPostAt(Date postAt) {
        this.postAt = postAt;
    }
}