package com.example.domain;

public class Bookmark {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bookmarks.id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bookmarks.memory_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private Integer memoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bookmarks.user_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bookmarks.id
     *
     * @return the value of bookmarks.id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bookmarks.id
     *
     * @param id the value for bookmarks.id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bookmarks.memory_id
     *
     * @return the value of bookmarks.memory_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public Integer getMemoryId() {
        return memoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bookmarks.memory_id
     *
     * @param memoryId the value for bookmarks.memory_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setMemoryId(Integer memoryId) {
        this.memoryId = memoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bookmarks.user_id
     *
     * @return the value of bookmarks.user_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bookmarks.user_id
     *
     * @param userId the value for bookmarks.user_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}