package com.example.domain;

public class CategoryContents {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category_contents.id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category_contents.category_name
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private String categoryName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category_contents.id
     *
     * @return the value of category_contents.id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category_contents.id
     *
     * @param id the value for category_contents.id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category_contents.category_name
     *
     * @return the value of category_contents.category_name
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public String getCategoryName() {
        return categoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category_contents.category_name
     *
     * @param categoryName the value for category_contents.category_name
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName == null ? null : categoryName.trim();
    }
}