package com.example.domain;

import java.util.Date;

public class CheckItem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_items.id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_items.check_title
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private String checkTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_items.category_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private Integer categoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_items.tab_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private Integer tabId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_items.is_shared
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private Byte isShared;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_items.creator_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private Integer creatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_items.created_at
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_items.updater_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private Integer updaterId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_items.updated_at
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private Date updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_items.is_checked
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private Byte isChecked;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_items.version
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_items.id
     *
     * @return the value of check_items.id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_items.id
     *
     * @param id the value for check_items.id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_items.check_title
     *
     * @return the value of check_items.check_title
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public String getCheckTitle() {
        return checkTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_items.check_title
     *
     * @param checkTitle the value for check_items.check_title
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setCheckTitle(String checkTitle) {
        this.checkTitle = checkTitle == null ? null : checkTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_items.category_id
     *
     * @return the value of check_items.category_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_items.category_id
     *
     * @param categoryId the value for check_items.category_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_items.tab_id
     *
     * @return the value of check_items.tab_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public Integer getTabId() {
        return tabId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_items.tab_id
     *
     * @param tabId the value for check_items.tab_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setTabId(Integer tabId) {
        this.tabId = tabId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_items.is_shared
     *
     * @return the value of check_items.is_shared
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public Byte getIsShared() {
        return isShared;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_items.is_shared
     *
     * @param isShared the value for check_items.is_shared
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setIsShared(Byte isShared) {
        this.isShared = isShared;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_items.creator_id
     *
     * @return the value of check_items.creator_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public Integer getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_items.creator_id
     *
     * @param creatorId the value for check_items.creator_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setCreatorId(Integer creatorId) {
        this.creatorId = creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_items.created_at
     *
     * @return the value of check_items.created_at
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_items.created_at
     *
     * @param createdAt the value for check_items.created_at
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_items.updater_id
     *
     * @return the value of check_items.updater_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public Integer getUpdaterId() {
        return updaterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_items.updater_id
     *
     * @param updaterId the value for check_items.updater_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setUpdaterId(Integer updaterId) {
        this.updaterId = updaterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_items.updated_at
     *
     * @return the value of check_items.updated_at
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_items.updated_at
     *
     * @param updatedAt the value for check_items.updated_at
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_items.is_checked
     *
     * @return the value of check_items.is_checked
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public Byte getIsChecked() {
        return isChecked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_items.is_checked
     *
     * @param isChecked the value for check_items.is_checked
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setIsChecked(Byte isChecked) {
        this.isChecked = isChecked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_items.version
     *
     * @return the value of check_items.version
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_items.version
     *
     * @param version the value for check_items.version
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}