package com.example.domain;

import java.util.Date;

public class Costs {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column costs.id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column costs.shiori_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private Integer shioriId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column costs.cost_category_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private Integer costCategoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column costs.cost
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private Integer cost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column costs.is_individual
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private Byte isIndividual;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column costs.title
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column costs.payer_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private Integer payerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column costs.creator_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private Integer creatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column costs.created_at
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column costs.updater_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private Integer updaterId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column costs.updated_at
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private Date updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column costs.version
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column costs.id
     *
     * @return the value of costs.id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column costs.id
     *
     * @param id the value for costs.id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column costs.shiori_id
     *
     * @return the value of costs.shiori_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public Integer getShioriId() {
        return shioriId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column costs.shiori_id
     *
     * @param shioriId the value for costs.shiori_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setShioriId(Integer shioriId) {
        this.shioriId = shioriId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column costs.cost_category_id
     *
     * @return the value of costs.cost_category_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public Integer getCostCategoryId() {
        return costCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column costs.cost_category_id
     *
     * @param costCategoryId the value for costs.cost_category_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setCostCategoryId(Integer costCategoryId) {
        this.costCategoryId = costCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column costs.cost
     *
     * @return the value of costs.cost
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public Integer getCost() {
        return cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column costs.cost
     *
     * @param cost the value for costs.cost
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setCost(Integer cost) {
        this.cost = cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column costs.is_individual
     *
     * @return the value of costs.is_individual
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public Byte getIsIndividual() {
        return isIndividual;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column costs.is_individual
     *
     * @param isIndividual the value for costs.is_individual
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setIsIndividual(Byte isIndividual) {
        this.isIndividual = isIndividual;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column costs.title
     *
     * @return the value of costs.title
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column costs.title
     *
     * @param title the value for costs.title
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column costs.payer_id
     *
     * @return the value of costs.payer_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public Integer getPayerId() {
        return payerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column costs.payer_id
     *
     * @param payerId the value for costs.payer_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setPayerId(Integer payerId) {
        this.payerId = payerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column costs.creator_id
     *
     * @return the value of costs.creator_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public Integer getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column costs.creator_id
     *
     * @param creatorId the value for costs.creator_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setCreatorId(Integer creatorId) {
        this.creatorId = creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column costs.created_at
     *
     * @return the value of costs.created_at
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column costs.created_at
     *
     * @param createdAt the value for costs.created_at
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column costs.updater_id
     *
     * @return the value of costs.updater_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public Integer getUpdaterId() {
        return updaterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column costs.updater_id
     *
     * @param updaterId the value for costs.updater_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setUpdaterId(Integer updaterId) {
        this.updaterId = updaterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column costs.updated_at
     *
     * @return the value of costs.updated_at
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column costs.updated_at
     *
     * @param updatedAt the value for costs.updated_at
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column costs.version
     *
     * @return the value of costs.version
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column costs.version
     *
     * @param version the value for costs.version
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}