package com.example.domain;

import java.util.Date;

public class Destinations {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column destinations.id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column destinations.shiori_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private Integer shioriId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column destinations.destination
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private String destination;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column destinations.creator_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private Integer creatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column destinations.created_at
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column destinations.updater_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private Integer updaterId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column destinations.updated_at
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private Date updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column destinations.version
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column destinations.id
     *
     * @return the value of destinations.id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column destinations.id
     *
     * @param id the value for destinations.id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column destinations.shiori_id
     *
     * @return the value of destinations.shiori_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public Integer getShioriId() {
        return shioriId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column destinations.shiori_id
     *
     * @param shioriId the value for destinations.shiori_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setShioriId(Integer shioriId) {
        this.shioriId = shioriId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column destinations.destination
     *
     * @return the value of destinations.destination
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public String getDestination() {
        return destination;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column destinations.destination
     *
     * @param destination the value for destinations.destination
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setDestination(String destination) {
        this.destination = destination == null ? null : destination.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column destinations.creator_id
     *
     * @return the value of destinations.creator_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public Integer getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column destinations.creator_id
     *
     * @param creatorId the value for destinations.creator_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setCreatorId(Integer creatorId) {
        this.creatorId = creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column destinations.created_at
     *
     * @return the value of destinations.created_at
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column destinations.created_at
     *
     * @param createdAt the value for destinations.created_at
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column destinations.updater_id
     *
     * @return the value of destinations.updater_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public Integer getUpdaterId() {
        return updaterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column destinations.updater_id
     *
     * @param updaterId the value for destinations.updater_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setUpdaterId(Integer updaterId) {
        this.updaterId = updaterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column destinations.updated_at
     *
     * @return the value of destinations.updated_at
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column destinations.updated_at
     *
     * @param updatedAt the value for destinations.updated_at
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column destinations.version
     *
     * @return the value of destinations.version
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column destinations.version
     *
     * @param version the value for destinations.version
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}