package com.example.domain;

public class HadCostCategories {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column had_cost_categories.id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column had_cost_categories.cost_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private Integer costId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column had_cost_categories.cost_category_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private Integer costCategoryId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column had_cost_categories.id
     *
     * @return the value of had_cost_categories.id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column had_cost_categories.id
     *
     * @param id the value for had_cost_categories.id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column had_cost_categories.cost_id
     *
     * @return the value of had_cost_categories.cost_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public Integer getCostId() {
        return costId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column had_cost_categories.cost_id
     *
     * @param costId the value for had_cost_categories.cost_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setCostId(Integer costId) {
        this.costId = costId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column had_cost_categories.cost_category_id
     *
     * @return the value of had_cost_categories.cost_category_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public Integer getCostCategoryId() {
        return costCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column had_cost_categories.cost_category_id
     *
     * @param costCategoryId the value for had_cost_categories.cost_category_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setCostCategoryId(Integer costCategoryId) {
        this.costCategoryId = costCategoryId;
    }
}