package com.example.domain;

public class HadHashtags {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column had_hashtags.id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column had_hashtags.memory_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private Integer memoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column had_hashtags.hashtag_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private Integer hashtagId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column had_hashtags.id
     *
     * @return the value of had_hashtags.id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column had_hashtags.id
     *
     * @param id the value for had_hashtags.id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column had_hashtags.memory_id
     *
     * @return the value of had_hashtags.memory_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public Integer getMemoryId() {
        return memoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column had_hashtags.memory_id
     *
     * @param memoryId the value for had_hashtags.memory_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setMemoryId(Integer memoryId) {
        this.memoryId = memoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column had_hashtags.hashtag_id
     *
     * @return the value of had_hashtags.hashtag_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public Integer getHashtagId() {
        return hashtagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column had_hashtags.hashtag_id
     *
     * @param hashtagId the value for had_hashtags.hashtag_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setHashtagId(Integer hashtagId) {
        this.hashtagId = hashtagId;
    }
}