package com.example.domain;

import java.util.Date;

public class IndividualCost {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column individual_costs.id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column individual_costs.cost_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private Integer costId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column individual_costs.individual_user_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private Integer individualUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column individual_costs.individual_cost
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private Integer individualCost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column individual_costs.creator_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private Integer creatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column individual_costs.created_at
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column individual_costs.updater_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private Integer updaterId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column individual_costs.updated_at
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private Date updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column individual_costs.version
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column individual_costs.id
     *
     * @return the value of individual_costs.id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column individual_costs.id
     *
     * @param id the value for individual_costs.id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column individual_costs.cost_id
     *
     * @return the value of individual_costs.cost_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public Integer getCostId() {
        return costId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column individual_costs.cost_id
     *
     * @param costId the value for individual_costs.cost_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setCostId(Integer costId) {
        this.costId = costId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column individual_costs.individual_user_id
     *
     * @return the value of individual_costs.individual_user_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public Integer getIndividualUserId() {
        return individualUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column individual_costs.individual_user_id
     *
     * @param individualUserId the value for individual_costs.individual_user_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setIndividualUserId(Integer individualUserId) {
        this.individualUserId = individualUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column individual_costs.individual_cost
     *
     * @return the value of individual_costs.individual_cost
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public Integer getIndividualCost() {
        return individualCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column individual_costs.individual_cost
     *
     * @param individualCost the value for individual_costs.individual_cost
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setIndividualCost(Integer individualCost) {
        this.individualCost = individualCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column individual_costs.creator_id
     *
     * @return the value of individual_costs.creator_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public Integer getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column individual_costs.creator_id
     *
     * @param creatorId the value for individual_costs.creator_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setCreatorId(Integer creatorId) {
        this.creatorId = creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column individual_costs.created_at
     *
     * @return the value of individual_costs.created_at
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column individual_costs.created_at
     *
     * @param createdAt the value for individual_costs.created_at
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column individual_costs.updater_id
     *
     * @return the value of individual_costs.updater_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public Integer getUpdaterId() {
        return updaterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column individual_costs.updater_id
     *
     * @param updaterId the value for individual_costs.updater_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setUpdaterId(Integer updaterId) {
        this.updaterId = updaterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column individual_costs.updated_at
     *
     * @return the value of individual_costs.updated_at
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column individual_costs.updated_at
     *
     * @param updatedAt the value for individual_costs.updated_at
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column individual_costs.version
     *
     * @return the value of individual_costs.version
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column individual_costs.version
     *
     * @param version the value for individual_costs.version
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}