package com.example.domain;

public class Members {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column members.id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column members.shiori_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private Integer shioriId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column members.user_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column members.id
     *
     * @return the value of members.id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column members.id
     *
     * @param id the value for members.id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column members.shiori_id
     *
     * @return the value of members.shiori_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public Integer getShioriId() {
        return shioriId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column members.shiori_id
     *
     * @param shioriId the value for members.shiori_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setShioriId(Integer shioriId) {
        this.shioriId = shioriId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column members.user_id
     *
     * @return the value of members.user_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column members.user_id
     *
     * @param userId the value for members.user_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}