package com.example.domain;

import java.util.Date;

public class MemoImage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memo_images.id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memo_images.memo_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private Integer memoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memo_images.image_path
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private String imagePath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memo_images.creator_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private Integer creatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memo_images.created_at
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private Date createdAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memo_images.id
     *
     * @return the value of memo_images.id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memo_images.id
     *
     * @param id the value for memo_images.id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memo_images.memo_id
     *
     * @return the value of memo_images.memo_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public Integer getMemoId() {
        return memoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memo_images.memo_id
     *
     * @param memoId the value for memo_images.memo_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setMemoId(Integer memoId) {
        this.memoId = memoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memo_images.image_path
     *
     * @return the value of memo_images.image_path
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public String getImagePath() {
        return imagePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memo_images.image_path
     *
     * @param imagePath the value for memo_images.image_path
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setImagePath(String imagePath) {
        this.imagePath = imagePath == null ? null : imagePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memo_images.creator_id
     *
     * @return the value of memo_images.creator_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public Integer getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memo_images.creator_id
     *
     * @param creatorId the value for memo_images.creator_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setCreatorId(Integer creatorId) {
        this.creatorId = creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memo_images.created_at
     *
     * @return the value of memo_images.created_at
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memo_images.created_at
     *
     * @param createdAt the value for memo_images.created_at
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
}