package com.example.domain;

public class MemoryImage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memory_images.id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memory_images.memory_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private Integer memoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memory_images.image_path
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private String imagePath;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memory_images.id
     *
     * @return the value of memory_images.id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memory_images.id
     *
     * @param id the value for memory_images.id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memory_images.memory_id
     *
     * @return the value of memory_images.memory_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public Integer getMemoryId() {
        return memoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memory_images.memory_id
     *
     * @param memoryId the value for memory_images.memory_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setMemoryId(Integer memoryId) {
        this.memoryId = memoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memory_images.image_path
     *
     * @return the value of memory_images.image_path
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public String getImagePath() {
        return imagePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memory_images.image_path
     *
     * @param imagePath the value for memory_images.image_path
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setImagePath(String imagePath) {
        this.imagePath = imagePath == null ? null : imagePath.trim();
    }
}