package com.example.domain;

public class Reads {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reads.id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reads.user_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reads.message_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private Integer messageId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reads.is_read
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private Byte isRead;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reads.id
     *
     * @return the value of reads.id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reads.id
     *
     * @param id the value for reads.id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reads.user_id
     *
     * @return the value of reads.user_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reads.user_id
     *
     * @param userId the value for reads.user_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reads.message_id
     *
     * @return the value of reads.message_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public Integer getMessageId() {
        return messageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reads.message_id
     *
     * @param messageId the value for reads.message_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setMessageId(Integer messageId) {
        this.messageId = messageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reads.is_read
     *
     * @return the value of reads.is_read
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public Byte getIsRead() {
        return isRead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reads.is_read
     *
     * @param isRead the value for reads.is_read
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setIsRead(Byte isRead) {
        this.isRead = isRead;
    }
}