package com.example.domain;

import java.util.Date;

public class ScheForPost {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sche_for_posts.id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sche_for_posts.schedule_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private Integer scheduleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sche_for_posts.shiori_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private Integer shioriId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sche_for_posts.memory_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private Integer memoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sche_for_posts.title
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sche_for_posts.start_at
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private Date startAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sche_for_posts.finish_at
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private Date finishAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sche_for_posts.date
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sche_for_posts.icon_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private Integer iconId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sche_for_posts.tel
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private String tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sche_for_posts.destination
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private String destination;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sche_for_posts.url
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sche_for_posts.address
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sche_for_posts.memo
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private String memo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sche_for_posts.cost
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private Integer cost;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sche_for_posts.id
     *
     * @return the value of sche_for_posts.id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sche_for_posts.id
     *
     * @param id the value for sche_for_posts.id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sche_for_posts.schedule_id
     *
     * @return the value of sche_for_posts.schedule_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public Integer getScheduleId() {
        return scheduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sche_for_posts.schedule_id
     *
     * @param scheduleId the value for sche_for_posts.schedule_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setScheduleId(Integer scheduleId) {
        this.scheduleId = scheduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sche_for_posts.shiori_id
     *
     * @return the value of sche_for_posts.shiori_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public Integer getShioriId() {
        return shioriId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sche_for_posts.shiori_id
     *
     * @param shioriId the value for sche_for_posts.shiori_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setShioriId(Integer shioriId) {
        this.shioriId = shioriId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sche_for_posts.memory_id
     *
     * @return the value of sche_for_posts.memory_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public Integer getMemoryId() {
        return memoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sche_for_posts.memory_id
     *
     * @param memoryId the value for sche_for_posts.memory_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setMemoryId(Integer memoryId) {
        this.memoryId = memoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sche_for_posts.title
     *
     * @return the value of sche_for_posts.title
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sche_for_posts.title
     *
     * @param title the value for sche_for_posts.title
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sche_for_posts.start_at
     *
     * @return the value of sche_for_posts.start_at
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public Date getStartAt() {
        return startAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sche_for_posts.start_at
     *
     * @param startAt the value for sche_for_posts.start_at
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setStartAt(Date startAt) {
        this.startAt = startAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sche_for_posts.finish_at
     *
     * @return the value of sche_for_posts.finish_at
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public Date getFinishAt() {
        return finishAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sche_for_posts.finish_at
     *
     * @param finishAt the value for sche_for_posts.finish_at
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setFinishAt(Date finishAt) {
        this.finishAt = finishAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sche_for_posts.date
     *
     * @return the value of sche_for_posts.date
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sche_for_posts.date
     *
     * @param date the value for sche_for_posts.date
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sche_for_posts.icon_id
     *
     * @return the value of sche_for_posts.icon_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public Integer getIconId() {
        return iconId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sche_for_posts.icon_id
     *
     * @param iconId the value for sche_for_posts.icon_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setIconId(Integer iconId) {
        this.iconId = iconId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sche_for_posts.tel
     *
     * @return the value of sche_for_posts.tel
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sche_for_posts.tel
     *
     * @param tel the value for sche_for_posts.tel
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sche_for_posts.destination
     *
     * @return the value of sche_for_posts.destination
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public String getDestination() {
        return destination;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sche_for_posts.destination
     *
     * @param destination the value for sche_for_posts.destination
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setDestination(String destination) {
        this.destination = destination == null ? null : destination.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sche_for_posts.url
     *
     * @return the value of sche_for_posts.url
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sche_for_posts.url
     *
     * @param url the value for sche_for_posts.url
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sche_for_posts.address
     *
     * @return the value of sche_for_posts.address
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sche_for_posts.address
     *
     * @param address the value for sche_for_posts.address
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sche_for_posts.memo
     *
     * @return the value of sche_for_posts.memo
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sche_for_posts.memo
     *
     * @param memo the value for sche_for_posts.memo
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sche_for_posts.cost
     *
     * @return the value of sche_for_posts.cost
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public Integer getCost() {
        return cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sche_for_posts.cost
     *
     * @param cost the value for sche_for_posts.cost
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setCost(Integer cost) {
        this.cost = cost;
    }
}