package com.example.domain;

import java.util.Date;

public class Schedules {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedules.id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedules.shiori_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private Integer shioriId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedules.title
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedules.start_at
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private Date startAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedules.finish_at
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private Date finishAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedules.date
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedules.icon_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private Integer iconId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedules.destination
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private String destination;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedules.address
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedules.tel
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private String tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedules.memo
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private String memo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedules.cost
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private Integer cost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedules.creator_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private Integer creatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedules.created_at
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedules.updater_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private Integer updaterId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedules.updated_at
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private Date updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedules.version
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedules.url
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private String url;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedules.id
     *
     * @return the value of schedules.id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedules.id
     *
     * @param id the value for schedules.id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedules.shiori_id
     *
     * @return the value of schedules.shiori_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public Integer getShioriId() {
        return shioriId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedules.shiori_id
     *
     * @param shioriId the value for schedules.shiori_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setShioriId(Integer shioriId) {
        this.shioriId = shioriId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedules.title
     *
     * @return the value of schedules.title
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedules.title
     *
     * @param title the value for schedules.title
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedules.start_at
     *
     * @return the value of schedules.start_at
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public Date getStartAt() {
        return startAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedules.start_at
     *
     * @param startAt the value for schedules.start_at
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setStartAt(Date startAt) {
        this.startAt = startAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedules.finish_at
     *
     * @return the value of schedules.finish_at
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public Date getFinishAt() {
        return finishAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedules.finish_at
     *
     * @param finishAt the value for schedules.finish_at
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setFinishAt(Date finishAt) {
        this.finishAt = finishAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedules.date
     *
     * @return the value of schedules.date
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedules.date
     *
     * @param date the value for schedules.date
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedules.icon_id
     *
     * @return the value of schedules.icon_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public Integer getIconId() {
        return iconId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedules.icon_id
     *
     * @param iconId the value for schedules.icon_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setIconId(Integer iconId) {
        this.iconId = iconId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedules.destination
     *
     * @return the value of schedules.destination
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public String getDestination() {
        return destination;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedules.destination
     *
     * @param destination the value for schedules.destination
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setDestination(String destination) {
        this.destination = destination == null ? null : destination.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedules.address
     *
     * @return the value of schedules.address
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedules.address
     *
     * @param address the value for schedules.address
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedules.tel
     *
     * @return the value of schedules.tel
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedules.tel
     *
     * @param tel the value for schedules.tel
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedules.memo
     *
     * @return the value of schedules.memo
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedules.memo
     *
     * @param memo the value for schedules.memo
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedules.cost
     *
     * @return the value of schedules.cost
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public Integer getCost() {
        return cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedules.cost
     *
     * @param cost the value for schedules.cost
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setCost(Integer cost) {
        this.cost = cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedules.creator_id
     *
     * @return the value of schedules.creator_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public Integer getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedules.creator_id
     *
     * @param creatorId the value for schedules.creator_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setCreatorId(Integer creatorId) {
        this.creatorId = creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedules.created_at
     *
     * @return the value of schedules.created_at
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedules.created_at
     *
     * @param createdAt the value for schedules.created_at
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedules.updater_id
     *
     * @return the value of schedules.updater_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public Integer getUpdaterId() {
        return updaterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedules.updater_id
     *
     * @param updaterId the value for schedules.updater_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setUpdaterId(Integer updaterId) {
        this.updaterId = updaterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedules.updated_at
     *
     * @return the value of schedules.updated_at
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedules.updated_at
     *
     * @param updatedAt the value for schedules.updated_at
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedules.version
     *
     * @return the value of schedules.version
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedules.version
     *
     * @param version the value for schedules.version
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedules.url
     *
     * @return the value of schedules.url
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedules.url
     *
     * @param url the value for schedules.url
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }
}