package com.example.domain;

public class TabContents {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_contents.id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_contents.tab_name
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private String tabName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_contents.id
     *
     * @return the value of tab_contents.id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_contents.id
     *
     * @param id the value for tab_contents.id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_contents.tab_name
     *
     * @return the value of tab_contents.tab_name
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public String getTabName() {
        return tabName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_contents.tab_name
     *
     * @param tabName the value for tab_contents.tab_name
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setTabName(String tabName) {
        this.tabName = tabName == null ? null : tabName.trim();
    }
}