package com.example.mapper;

import com.example.domain.Bookmarks;
import com.example.domain.BookmarksExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BookmarksMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookmarks
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int countByExample(BookmarksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookmarks
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int deleteByExample(BookmarksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookmarks
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookmarks
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int insert(Bookmarks record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookmarks
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int insertSelective(Bookmarks record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookmarks
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    List<Bookmarks> selectByExample(BookmarksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookmarks
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    Bookmarks selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookmarks
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByExampleSelective(@Param("record") Bookmarks record, @Param("example") BookmarksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookmarks
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByExample(@Param("record") Bookmarks record, @Param("example") BookmarksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookmarks
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByPrimaryKeySelective(Bookmarks record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookmarks
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByPrimaryKey(Bookmarks record);
}