package com.example.mapper;

import com.example.domain.CategoryContents;
import com.example.domain.CategoryContentsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CategoryContentsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_contents
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int countByExample(CategoryContentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_contents
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int deleteByExample(CategoryContentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_contents
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_contents
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int insert(CategoryContents record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_contents
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int insertSelective(CategoryContents record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_contents
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    List<CategoryContents> selectByExample(CategoryContentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_contents
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    CategoryContents selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_contents
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByExampleSelective(@Param("record") CategoryContents record, @Param("example") CategoryContentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_contents
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByExample(@Param("record") CategoryContents record, @Param("example") CategoryContentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_contents
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByPrimaryKeySelective(CategoryContents record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_contents
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByPrimaryKey(CategoryContents record);
}