package com.example.mapper;

import com.example.domain.CheckItems;
import com.example.domain.CheckItemsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CheckItemsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_items
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int countByExample(CheckItemsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_items
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int deleteByExample(CheckItemsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_items
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_items
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int insert(CheckItems record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_items
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int insertSelective(CheckItems record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_items
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    List<CheckItems> selectByExample(CheckItemsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_items
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    CheckItems selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_items
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByExampleSelective(@Param("record") CheckItems record, @Param("example") CheckItemsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_items
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByExample(@Param("record") CheckItems record, @Param("example") CheckItemsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_items
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByPrimaryKeySelective(CheckItems record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_items
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByPrimaryKey(CheckItems record);
}