package com.example.mapper;

import com.example.domain.Contacts;
import com.example.domain.ContactsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ContactsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contacts
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int countByExample(ContactsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contacts
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int deleteByExample(ContactsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contacts
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contacts
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int insert(Contacts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contacts
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int insertSelective(Contacts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contacts
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    List<Contacts> selectByExample(ContactsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contacts
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    Contacts selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contacts
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByExampleSelective(@Param("record") Contacts record, @Param("example") ContactsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contacts
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByExample(@Param("record") Contacts record, @Param("example") ContactsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contacts
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByPrimaryKeySelective(Contacts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contacts
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByPrimaryKey(Contacts record);
}