package com.example.mapper;

import com.example.domain.Cost;
import com.example.example.CostExample;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CostMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table costs
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int countByExample(CostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table costs
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int deleteByExample(CostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table costs
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table costs
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int insert(Cost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table costs
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int insertSelective(Cost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table costs
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    List<Cost> selectByExample(CostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table costs
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    Cost selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table costs
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByExampleSelective(@Param("record") Cost record, @Param("example") CostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table costs
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByExample(@Param("record") Cost record, @Param("example") CostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table costs
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByPrimaryKeySelective(Cost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table costs
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByPrimaryKey(Cost record);
}