package com.example.mapper;

import com.example.domain.Costs;
import com.example.domain.CostsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CostsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table costs
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int countByExample(CostsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table costs
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int deleteByExample(CostsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table costs
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table costs
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int insert(Costs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table costs
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int insertSelective(Costs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table costs
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    List<Costs> selectByExample(CostsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table costs
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    Costs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table costs
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByExampleSelective(@Param("record") Costs record, @Param("example") CostsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table costs
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByExample(@Param("record") Costs record, @Param("example") CostsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table costs
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByPrimaryKeySelective(Costs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table costs
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByPrimaryKey(Costs record);
}