package com.example.mapper;

import com.example.domain.CostCategories;
import com.example.domain.CostCategoriesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CostCategoriesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cost_categories
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int countByExample(CostCategoriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cost_categories
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int deleteByExample(CostCategoriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cost_categories
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cost_categories
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int insert(CostCategories record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cost_categories
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int insertSelective(CostCategories record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cost_categories
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    List<CostCategories> selectByExample(CostCategoriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cost_categories
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    CostCategories selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cost_categories
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByExampleSelective(@Param("record") CostCategories record, @Param("example") CostCategoriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cost_categories
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByExample(@Param("record") CostCategories record, @Param("example") CostCategoriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cost_categories
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByPrimaryKeySelective(CostCategories record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cost_categories
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByPrimaryKey(CostCategories record);
}