package com.example.mapper;

import com.example.domain.Destination;
import com.example.example.DestinationExample;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DestinationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table destinations
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int countByExample(DestinationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table destinations
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int deleteByExample(DestinationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table destinations
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table destinations
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int insert(Destination record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table destinations
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int insertSelective(Destination record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table destinations
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    List<Destination> selectByExample(DestinationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table destinations
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    Destination selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table destinations
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByExampleSelective(@Param("record") Destination record, @Param("example") DestinationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table destinations
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByExample(@Param("record") Destination record, @Param("example") DestinationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table destinations
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByPrimaryKeySelective(Destination record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table destinations
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByPrimaryKey(Destination record);
}