package com.example.mapper;

import com.example.domain.Destinations;
import com.example.domain.DestinationsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DestinationsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table destinations
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int countByExample(DestinationsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table destinations
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int deleteByExample(DestinationsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table destinations
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table destinations
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int insert(Destinations record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table destinations
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int insertSelective(Destinations record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table destinations
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    List<Destinations> selectByExample(DestinationsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table destinations
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    Destinations selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table destinations
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByExampleSelective(@Param("record") Destinations record, @Param("example") DestinationsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table destinations
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByExample(@Param("record") Destinations record, @Param("example") DestinationsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table destinations
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByPrimaryKeySelective(Destinations record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table destinations
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByPrimaryKey(Destinations record);
}