package com.example.mapper;

import com.example.domain.HadCostCategories;
import com.example.domain.HadCostCategoriesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HadCostCategoriesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table had_cost_categories
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int countByExample(HadCostCategoriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table had_cost_categories
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int deleteByExample(HadCostCategoriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table had_cost_categories
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table had_cost_categories
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int insert(HadCostCategories record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table had_cost_categories
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int insertSelective(HadCostCategories record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table had_cost_categories
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    List<HadCostCategories> selectByExample(HadCostCategoriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table had_cost_categories
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    HadCostCategories selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table had_cost_categories
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByExampleSelective(@Param("record") HadCostCategories record, @Param("example") HadCostCategoriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table had_cost_categories
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByExample(@Param("record") HadCostCategories record, @Param("example") HadCostCategoriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table had_cost_categories
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByPrimaryKeySelective(HadCostCategories record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table had_cost_categories
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByPrimaryKey(HadCostCategories record);
}