package com.example.mapper;

import com.example.domain.HadHashtag;
import com.example.example.HadHashtagExample;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HadHashtagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table had_hashtags
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int countByExample(HadHashtagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table had_hashtags
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int deleteByExample(HadHashtagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table had_hashtags
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table had_hashtags
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int insert(HadHashtag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table had_hashtags
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int insertSelective(HadHashtag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table had_hashtags
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    List<HadHashtag> selectByExample(HadHashtagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table had_hashtags
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    HadHashtag selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table had_hashtags
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByExampleSelective(@Param("record") HadHashtag record, @Param("example") HadHashtagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table had_hashtags
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByExample(@Param("record") HadHashtag record, @Param("example") HadHashtagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table had_hashtags
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByPrimaryKeySelective(HadHashtag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table had_hashtags
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByPrimaryKey(HadHashtag record);
}