package com.example.mapper;

import com.example.domain.IndividualCost;
import com.example.example.IndividualCostExample;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IndividualCostMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table individual_costs
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int countByExample(IndividualCostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table individual_costs
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int deleteByExample(IndividualCostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table individual_costs
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table individual_costs
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int insert(IndividualCost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table individual_costs
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int insertSelective(IndividualCost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table individual_costs
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    List<IndividualCost> selectByExample(IndividualCostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table individual_costs
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    IndividualCost selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table individual_costs
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByExampleSelective(@Param("record") IndividualCost record, @Param("example") IndividualCostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table individual_costs
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByExample(@Param("record") IndividualCost record, @Param("example") IndividualCostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table individual_costs
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByPrimaryKeySelective(IndividualCost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table individual_costs
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByPrimaryKey(IndividualCost record);
}