package com.example.mapper;

import com.example.domain.IndividualCosts;
import com.example.domain.IndividualCostsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IndividualCostsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table individual_costs
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int countByExample(IndividualCostsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table individual_costs
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int deleteByExample(IndividualCostsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table individual_costs
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table individual_costs
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int insert(IndividualCosts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table individual_costs
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int insertSelective(IndividualCosts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table individual_costs
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    List<IndividualCosts> selectByExample(IndividualCostsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table individual_costs
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    IndividualCosts selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table individual_costs
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByExampleSelective(@Param("record") IndividualCosts record, @Param("example") IndividualCostsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table individual_costs
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByExample(@Param("record") IndividualCosts record, @Param("example") IndividualCostsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table individual_costs
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByPrimaryKeySelective(IndividualCosts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table individual_costs
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByPrimaryKey(IndividualCosts record);
}