package com.example.mapper;

import com.example.domain.MemoryImages;
import com.example.domain.MemoryImagesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MemoryImagesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memory_images
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int countByExample(MemoryImagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memory_images
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int deleteByExample(MemoryImagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memory_images
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memory_images
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int insert(MemoryImages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memory_images
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int insertSelective(MemoryImages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memory_images
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    List<MemoryImages> selectByExample(MemoryImagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memory_images
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    MemoryImages selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memory_images
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByExampleSelective(@Param("record") MemoryImages record, @Param("example") MemoryImagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memory_images
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByExample(@Param("record") MemoryImages record, @Param("example") MemoryImagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memory_images
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByPrimaryKeySelective(MemoryImages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memory_images
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByPrimaryKey(MemoryImages record);
}