package com.example.mapper;

import com.example.domain.MemoImages;
import com.example.domain.MemoImagesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MemoImagesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memo_images
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int countByExample(MemoImagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memo_images
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int deleteByExample(MemoImagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memo_images
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memo_images
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int insert(MemoImages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memo_images
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int insertSelective(MemoImages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memo_images
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    List<MemoImages> selectByExample(MemoImagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memo_images
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    MemoImages selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memo_images
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByExampleSelective(@Param("record") MemoImages record, @Param("example") MemoImagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memo_images
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByExample(@Param("record") MemoImages record, @Param("example") MemoImagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memo_images
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByPrimaryKeySelective(MemoImages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memo_images
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByPrimaryKey(MemoImages record);
}