package com.example.mapper;

import com.example.domain.MemoryImage;
import com.example.example.MemoryImageExample;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MemoryImageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memory_images
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int countByExample(MemoryImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memory_images
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int deleteByExample(MemoryImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memory_images
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memory_images
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int insert(MemoryImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memory_images
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int insertSelective(MemoryImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memory_images
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    List<MemoryImage> selectByExample(MemoryImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memory_images
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    MemoryImage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memory_images
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByExampleSelective(@Param("record") MemoryImage record, @Param("example") MemoryImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memory_images
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByExample(@Param("record") MemoryImage record, @Param("example") MemoryImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memory_images
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByPrimaryKeySelective(MemoryImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memory_images
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByPrimaryKey(MemoryImage record);
}