package com.example.mapper;

import com.example.domain.Memos;
import com.example.domain.MemosExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MemosMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memos
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int countByExample(MemosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memos
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int deleteByExample(MemosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memos
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memos
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int insert(Memos record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memos
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int insertSelective(Memos record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memos
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    List<Memos> selectByExample(MemosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memos
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    Memos selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memos
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByExampleSelective(@Param("record") Memos record, @Param("example") MemosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memos
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByExample(@Param("record") Memos record, @Param("example") MemosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memos
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByPrimaryKeySelective(Memos record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memos
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByPrimaryKey(Memos record);
}