package com.example.mapper;

import com.example.domain.Reads;
import com.example.domain.ReadsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ReadsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reads
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int countByExample(ReadsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reads
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int deleteByExample(ReadsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reads
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reads
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int insert(Reads record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reads
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int insertSelective(Reads record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reads
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    List<Reads> selectByExample(ReadsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reads
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    Reads selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reads
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByExampleSelective(@Param("record") Reads record, @Param("example") ReadsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reads
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByExample(@Param("record") Reads record, @Param("example") ReadsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reads
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByPrimaryKeySelective(Reads record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reads
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByPrimaryKey(Reads record);
}