package com.example.mapper;

import com.example.domain.Read;
import com.example.example.ReadExample;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ReadMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reads
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int countByExample(ReadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reads
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int deleteByExample(ReadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reads
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reads
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int insert(Read record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reads
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int insertSelective(Read record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reads
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    List<Read> selectByExample(ReadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reads
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    Read selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reads
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByExampleSelective(@Param("record") Read record, @Param("example") ReadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reads
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByExample(@Param("record") Read record, @Param("example") ReadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reads
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByPrimaryKeySelective(Read record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reads
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByPrimaryKey(Read record);
}