package com.example.mapper;

import com.example.domain.ScheForPosts;
import com.example.domain.ScheForPostsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ScheForPostsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sche_for_posts
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int countByExample(ScheForPostsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sche_for_posts
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int deleteByExample(ScheForPostsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sche_for_posts
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sche_for_posts
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int insert(ScheForPosts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sche_for_posts
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int insertSelective(ScheForPosts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sche_for_posts
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    List<ScheForPosts> selectByExample(ScheForPostsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sche_for_posts
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    ScheForPosts selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sche_for_posts
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByExampleSelective(@Param("record") ScheForPosts record, @Param("example") ScheForPostsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sche_for_posts
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByExample(@Param("record") ScheForPosts record, @Param("example") ScheForPostsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sche_for_posts
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByPrimaryKeySelective(ScheForPosts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sche_for_posts
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByPrimaryKey(ScheForPosts record);
}