package com.example.mapper;

import com.example.domain.ScheduleIcons;
import com.example.domain.ScheduleIconsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ScheduleIconsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_icons
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int countByExample(ScheduleIconsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_icons
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int deleteByExample(ScheduleIconsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_icons
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_icons
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int insert(ScheduleIcons record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_icons
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int insertSelective(ScheduleIcons record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_icons
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    List<ScheduleIcons> selectByExample(ScheduleIconsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_icons
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    ScheduleIcons selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_icons
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByExampleSelective(@Param("record") ScheduleIcons record, @Param("example") ScheduleIconsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_icons
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByExample(@Param("record") ScheduleIcons record, @Param("example") ScheduleIconsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_icons
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByPrimaryKeySelective(ScheduleIcons record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_icons
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByPrimaryKey(ScheduleIcons record);
}