package com.example.mapper;

import com.example.domain.ScheduleIcon;
import com.example.example.ScheduleIconExample;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ScheduleIconMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_icons
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int countByExample(ScheduleIconExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_icons
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int deleteByExample(ScheduleIconExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_icons
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_icons
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int insert(ScheduleIcon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_icons
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int insertSelective(ScheduleIcon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_icons
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    List<ScheduleIcon> selectByExample(ScheduleIconExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_icons
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    ScheduleIcon selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_icons
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByExampleSelective(@Param("record") ScheduleIcon record, @Param("example") ScheduleIconExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_icons
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByExample(@Param("record") ScheduleIcon record, @Param("example") ScheduleIconExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_icons
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByPrimaryKeySelective(ScheduleIcon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_icons
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByPrimaryKey(ScheduleIcon record);
}