package com.example.mapper;

import com.example.domain.Schedules;
import com.example.domain.SchedulesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SchedulesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedules
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int countByExample(SchedulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedules
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int deleteByExample(SchedulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedules
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedules
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int insert(Schedules record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedules
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int insertSelective(Schedules record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedules
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    List<Schedules> selectByExampleWithBLOBs(SchedulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedules
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    List<Schedules> selectByExample(SchedulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedules
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    Schedules selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedules
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByExampleSelective(@Param("record") Schedules record, @Param("example") SchedulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedules
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByExampleWithBLOBs(@Param("record") Schedules record, @Param("example") SchedulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedules
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByExample(@Param("record") Schedules record, @Param("example") SchedulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedules
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByPrimaryKeySelective(Schedules record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedules
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByPrimaryKeyWithBLOBs(Schedules record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedules
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByPrimaryKey(Schedules record);
}