package com.example.mapper;

import com.example.domain.ScheForPost;
import com.example.example.ScheForPostExample;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ScheForPostMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sche_for_posts
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int countByExample(ScheForPostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sche_for_posts
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int deleteByExample(ScheForPostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sche_for_posts
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sche_for_posts
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int insert(ScheForPost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sche_for_posts
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int insertSelective(ScheForPost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sche_for_posts
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    List<ScheForPost> selectByExample(ScheForPostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sche_for_posts
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    ScheForPost selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sche_for_posts
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByExampleSelective(@Param("record") ScheForPost record, @Param("example") ScheForPostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sche_for_posts
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByExample(@Param("record") ScheForPost record, @Param("example") ScheForPostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sche_for_posts
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByPrimaryKeySelective(ScheForPost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sche_for_posts
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByPrimaryKey(ScheForPost record);
}