package com.example.mapper;

import com.example.domain.Shiori;
import com.example.example.ShioriExample;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ShioriMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shioris
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int countByExample(ShioriExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shioris
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int deleteByExample(ShioriExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shioris
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shioris
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int insert(Shiori record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shioris
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int insertSelective(Shiori record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shioris
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    List<Shiori> selectByExample(ShioriExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shioris
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    Shiori selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shioris
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByExampleSelective(@Param("record") Shiori record, @Param("example") ShioriExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shioris
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByExample(@Param("record") Shiori record, @Param("example") ShioriExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shioris
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByPrimaryKeySelective(Shiori record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shioris
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByPrimaryKey(Shiori record);
}