package com.example.mapper;

import com.example.domain.Shioris;
import com.example.domain.ShiorisExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ShiorisMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shioris
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int countByExample(ShiorisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shioris
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int deleteByExample(ShiorisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shioris
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shioris
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int insert(Shioris record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shioris
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int insertSelective(Shioris record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shioris
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    List<Shioris> selectByExample(ShiorisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shioris
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    Shioris selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shioris
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByExampleSelective(@Param("record") Shioris record, @Param("example") ShiorisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shioris
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByExample(@Param("record") Shioris record, @Param("example") ShiorisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shioris
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByPrimaryKeySelective(Shioris record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shioris
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByPrimaryKey(Shioris record);
}