package com.example.mapper;

import com.example.domain.SplitMembers;
import com.example.domain.SplitMembersExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SplitMembersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table split_members
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int countByExample(SplitMembersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table split_members
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int deleteByExample(SplitMembersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table split_members
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table split_members
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int insert(SplitMembers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table split_members
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int insertSelective(SplitMembers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table split_members
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    List<SplitMembers> selectByExample(SplitMembersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table split_members
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    SplitMembers selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table split_members
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByExampleSelective(@Param("record") SplitMembers record, @Param("example") SplitMembersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table split_members
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByExample(@Param("record") SplitMembers record, @Param("example") SplitMembersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table split_members
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByPrimaryKeySelective(SplitMembers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table split_members
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByPrimaryKey(SplitMembers record);
}