package com.example.mapper;

import com.example.domain.TabContents;
import com.example.domain.TabContentsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TabContentsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_contents
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int countByExample(TabContentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_contents
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int deleteByExample(TabContentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_contents
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_contents
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int insert(TabContents record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_contents
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int insertSelective(TabContents record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_contents
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    List<TabContents> selectByExample(TabContentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_contents
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    TabContents selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_contents
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByExampleSelective(@Param("record") TabContents record, @Param("example") TabContentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_contents
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByExample(@Param("record") TabContents record, @Param("example") TabContentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_contents
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByPrimaryKeySelective(TabContents record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_contents
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByPrimaryKey(TabContents record);
}