package com.example.mapper;

import com.example.domain.Tabs;
import com.example.domain.TabsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TabsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tabs
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int countByExample(TabsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tabs
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int deleteByExample(TabsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tabs
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tabs
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int insert(Tabs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tabs
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int insertSelective(Tabs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tabs
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    List<Tabs> selectByExample(TabsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tabs
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    Tabs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tabs
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByExampleSelective(@Param("record") Tabs record, @Param("example") TabsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tabs
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByExample(@Param("record") Tabs record, @Param("example") TabsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tabs
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByPrimaryKeySelective(Tabs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tabs
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByPrimaryKey(Tabs record);
}