package com.example.domain.scrap;

import java.util.Date;

public class Image {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column images.id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column images.scrap_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private Integer scrapId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column images.image_path
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private String imagePath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column images.creator_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private Integer creatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column images.created_at
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private Date createdAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column images.id
     *
     * @return the value of images.id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column images.id
     *
     * @param id the value for images.id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column images.scrap_id
     *
     * @return the value of images.scrap_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public Integer getScrapId() {
        return scrapId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column images.scrap_id
     *
     * @param scrapId the value for images.scrap_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setScrapId(Integer scrapId) {
        this.scrapId = scrapId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column images.image_path
     *
     * @return the value of images.image_path
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public String getImagePath() {
        return imagePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column images.image_path
     *
     * @param imagePath the value for images.image_path
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setImagePath(String imagePath) {
        this.imagePath = imagePath == null ? null : imagePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column images.creator_id
     *
     * @return the value of images.creator_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public Integer getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column images.creator_id
     *
     * @param creatorId the value for images.creator_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setCreatorId(Integer creatorId) {
        this.creatorId = creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column images.created_at
     *
     * @return the value of images.created_at
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column images.created_at
     *
     * @param createdAt the value for images.created_at
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
}