package com.example.domain.scrap;

import java.util.Date;

public class Scrap {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scraps.id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scraps.shiori_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private Integer shioriId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scraps.name
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scraps.creator_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private Integer creatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scraps.created_at
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scraps.updater_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private Integer updaterId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scraps.updated_at
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private Date updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scraps.version
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scraps.id
     *
     * @return the value of scraps.id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scraps.id
     *
     * @param id the value for scraps.id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scraps.shiori_id
     *
     * @return the value of scraps.shiori_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public Integer getShioriId() {
        return shioriId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scraps.shiori_id
     *
     * @param shioriId the value for scraps.shiori_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setShioriId(Integer shioriId) {
        this.shioriId = shioriId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scraps.name
     *
     * @return the value of scraps.name
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scraps.name
     *
     * @param name the value for scraps.name
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scraps.creator_id
     *
     * @return the value of scraps.creator_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public Integer getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scraps.creator_id
     *
     * @param creatorId the value for scraps.creator_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setCreatorId(Integer creatorId) {
        this.creatorId = creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scraps.created_at
     *
     * @return the value of scraps.created_at
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scraps.created_at
     *
     * @param createdAt the value for scraps.created_at
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scraps.updater_id
     *
     * @return the value of scraps.updater_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public Integer getUpdaterId() {
        return updaterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scraps.updater_id
     *
     * @param updaterId the value for scraps.updater_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setUpdaterId(Integer updaterId) {
        this.updaterId = updaterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scraps.updated_at
     *
     * @return the value of scraps.updated_at
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scraps.updated_at
     *
     * @param updatedAt the value for scraps.updated_at
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scraps.version
     *
     * @return the value of scraps.version
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scraps.version
     *
     * @param version the value for scraps.version
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}