package com.example.domain.schedule;

public class ScheduleIcon {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_icons.id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_icons.image_path
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private String imagePath;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_icons.id
     *
     * @return the value of schedule_icons.id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_icons.id
     *
     * @param id the value for schedule_icons.id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_icons.image_path
     *
     * @return the value of schedule_icons.image_path
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public String getImagePath() {
        return imagePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_icons.image_path
     *
     * @param imagePath the value for schedule_icons.image_path
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setImagePath(String imagePath) {
        this.imagePath = imagePath == null ? null : imagePath.trim();
    }
}