package com.example.mapper.checklist;

import com.example.domain.checklist.CheckItem;
import com.example.example.checklist.CheckItemExample;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CheckItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_items
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int countByExample(CheckItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_items
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int deleteByExample(CheckItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_items
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_items
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int insert(CheckItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_items
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int insertSelective(CheckItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_items
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    List<CheckItem> selectByExample(CheckItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_items
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    CheckItem selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_items
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByExampleSelective(@Param("record") CheckItem record, @Param("example") CheckItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_items
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByExample(@Param("record") CheckItem record, @Param("example") CheckItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_items
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByPrimaryKeySelective(CheckItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_items
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByPrimaryKey(CheckItem record);
}