package com.example.mapper.checklist;

import com.example.domain.checklist.TabContent;
import com.example.example.checklist.TabContentExample;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TabContentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_contents
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int countByExample(TabContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_contents
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int deleteByExample(TabContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_contents
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_contents
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int insert(TabContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_contents
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int insertSelective(TabContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_contents
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    List<TabContent> selectByExample(TabContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_contents
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    TabContent selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_contents
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByExampleSelective(@Param("record") TabContent record, @Param("example") TabContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_contents
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByExample(@Param("record") TabContent record, @Param("example") TabContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_contents
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByPrimaryKeySelective(TabContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_contents
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByPrimaryKey(TabContent record);
}