package com.example.mapper.memo;

import com.example.domain.memo.MemoImage;
import com.example.example.memo.MemoImageExample;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MemoImageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memo_images
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int countByExample(MemoImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memo_images
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int deleteByExample(MemoImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memo_images
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memo_images
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int insert(MemoImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memo_images
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int insertSelective(MemoImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memo_images
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    List<MemoImage> selectByExample(MemoImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memo_images
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    MemoImage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memo_images
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByExampleSelective(@Param("record") MemoImage record, @Param("example") MemoImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memo_images
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByExample(@Param("record") MemoImage record, @Param("example") MemoImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memo_images
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByPrimaryKeySelective(MemoImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memo_images
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByPrimaryKey(MemoImage record);
}