package com.example.mapper.memory;

import com.example.domain.memory.Bookmark;
import com.example.example.memory.BookmarkExample;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BookmarkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookmarks
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int countByExample(BookmarkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookmarks
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int deleteByExample(BookmarkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookmarks
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookmarks
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int insert(Bookmark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookmarks
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int insertSelective(Bookmark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookmarks
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    List<Bookmark> selectByExample(BookmarkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookmarks
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    Bookmark selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookmarks
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByExampleSelective(@Param("record") Bookmark record, @Param("example") BookmarkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookmarks
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByExample(@Param("record") Bookmark record, @Param("example") BookmarkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookmarks
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByPrimaryKeySelective(Bookmark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookmarks
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByPrimaryKey(Bookmark record);
}