package com.example.mapper.memory;

import com.example.domain.memory.Memory;
import com.example.example.memory.MemoryExample;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MemoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memories
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int countByExample(MemoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memories
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int deleteByExample(MemoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memories
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memories
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int insert(Memory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memories
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int insertSelective(Memory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memories
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    List<Memory> selectByExample(MemoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memories
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    Memory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memories
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByExampleSelective(@Param("record") Memory record, @Param("example") MemoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memories
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByExample(@Param("record") Memory record, @Param("example") MemoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memories
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByPrimaryKeySelective(Memory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memories
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    int updateByPrimaryKey(Memory record);
}