package com.example.domain.common;

import java.util.Date;

public class Contact {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contacts.id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contacts.name
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contacts.email
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contacts.content
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contacts.send_at
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private Date sendAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contacts.id
     *
     * @return the value of contacts.id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contacts.id
     *
     * @param id the value for contacts.id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contacts.name
     *
     * @return the value of contacts.name
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contacts.name
     *
     * @param name the value for contacts.name
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contacts.email
     *
     * @return the value of contacts.email
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contacts.email
     *
     * @param email the value for contacts.email
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contacts.content
     *
     * @return the value of contacts.content
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contacts.content
     *
     * @param content the value for contacts.content
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contacts.send_at
     *
     * @return the value of contacts.send_at
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public Date getSendAt() {
        return sendAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contacts.send_at
     *
     * @param sendAt the value for contacts.send_at
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setSendAt(Date sendAt) {
        this.sendAt = sendAt;
    }
}