package com.example.domain.cost;

public class CostCategory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cost_categories.id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cost_categories.cost_category_name
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private String costCategoryName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cost_categories.id
     *
     * @return the value of cost_categories.id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cost_categories.id
     *
     * @param id the value for cost_categories.id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cost_categories.cost_category_name
     *
     * @return the value of cost_categories.cost_category_name
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public String getCostCategoryName() {
        return costCategoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cost_categories.cost_category_name
     *
     * @param costCategoryName the value for cost_categories.cost_category_name
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setCostCategoryName(String costCategoryName) {
        this.costCategoryName = costCategoryName == null ? null : costCategoryName.trim();
    }
}