package com.example.domain.shiori;

import java.util.Date;

public class Shiori {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shioris.id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shioris.title
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shioris.dep_at
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private Date depAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shioris.return_at
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private Date returnAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shioris.image_path
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private String imagePath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shioris.creator_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private Integer creatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shioris.created_at
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shioris.updater_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private Integer updaterId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shioris.updated_at
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private Date updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shioris.version
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shioris.id
     *
     * @return the value of shioris.id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shioris.id
     *
     * @param id the value for shioris.id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shioris.title
     *
     * @return the value of shioris.title
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shioris.title
     *
     * @param title the value for shioris.title
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shioris.dep_at
     *
     * @return the value of shioris.dep_at
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public Date getDepAt() {
        return depAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shioris.dep_at
     *
     * @param depAt the value for shioris.dep_at
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setDepAt(Date depAt) {
        this.depAt = depAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shioris.return_at
     *
     * @return the value of shioris.return_at
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public Date getReturnAt() {
        return returnAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shioris.return_at
     *
     * @param returnAt the value for shioris.return_at
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setReturnAt(Date returnAt) {
        this.returnAt = returnAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shioris.image_path
     *
     * @return the value of shioris.image_path
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public String getImagePath() {
        return imagePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shioris.image_path
     *
     * @param imagePath the value for shioris.image_path
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setImagePath(String imagePath) {
        this.imagePath = imagePath == null ? null : imagePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shioris.creator_id
     *
     * @return the value of shioris.creator_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public Integer getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shioris.creator_id
     *
     * @param creatorId the value for shioris.creator_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setCreatorId(Integer creatorId) {
        this.creatorId = creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shioris.created_at
     *
     * @return the value of shioris.created_at
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shioris.created_at
     *
     * @param createdAt the value for shioris.created_at
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shioris.updater_id
     *
     * @return the value of shioris.updater_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public Integer getUpdaterId() {
        return updaterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shioris.updater_id
     *
     * @param updaterId the value for shioris.updater_id
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setUpdaterId(Integer updaterId) {
        this.updaterId = updaterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shioris.updated_at
     *
     * @return the value of shioris.updated_at
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shioris.updated_at
     *
     * @param updatedAt the value for shioris.updated_at
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shioris.version
     *
     * @return the value of shioris.version
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shioris.version
     *
     * @param version the value for shioris.version
     *
     * @mbggenerated Thu Oct 22 16:21:40 JST 2020
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}